### ISSUE TITLE
Latest IntelliJ 2023.2 is unusable with this plugin

### ISSUE THREAD

**Issue by santus444** [getappmap/appmap-intellij-plugin#372] opened 2023-08-27 03:34 UTC
And soon as I install this plug-in, my intellij  2023.2 became completely unresponsive. In order to use my ID E I had to launch it using CLI with plug-ins deactivated, and had to delete the plug-in. As soon as i launch my iDE  after installing the plug-in, it get hangs indefinitely.

**Comment by jansorg** [comment] 2023-08-28 08:11
Thanks for reporting!

1. IntelliJ generateds threadumps when a freeze is detected. Could you open the log folder (by `Help > Show logs in ...`) and attach a zip of subfolders `threadDumps-*` located inside the log folder? This would help to find the cause of this problem.
2. If possible, `idea.log` and `idea.1.log` would also be helpful to find the cause. Please note that these files may contain local paths, please review before attaching them. 
3. Could you also attach the data copied by `Help > About > Copy and close`, please?

Thank you for your help!

**Comment by kgilpin** [comment] 2023-08-28 11:50
@santus444 thanks for reporting this issue. We take this kind of problem very seriously because we know people need their plugins to be non intrusive. I would really appreciate it if you would provide the diagnostic information that Joachim requests!

**Comment by santus444** [comment] 2023-08-28 11:54
@jansorg / @kgilpin   sure. I can provide that. Can you please share any support email to which I can forward the files to? Want to avoid uploading log files here.

**Comment by jansorg** [comment] 2023-08-28 15:32
@santus444 Please send the data to kevin@appmap.io. Thanks!

**Comment by jansorg** [comment] 2023-09-06 13:49
@santus444 We've fixed a major issue, which could freeze the IDE, in 0.47. Could you try the latest version (0.48) and report if your problem is still showing up?

**Comment by santus444** [comment] 2023-09-06 14:53
Thanks. I am able to launch ide now. It does not freeze the ide anymore.

**Comment by santus444** [comment] 2023-09-06 14:54
> @santus444 if you have those logs available, please send them along!

I can check to see if I still have them as I removed earlier version.

**Comment by jansorg** [comment] 2023-09-06 14:54
Thank you for your reply! We're glad that the issue is fixed now.

**Closed by jansorg** 2023-09-06 14:54 UTC

**Comment by jansorg** [comment] 2023-09-06 14:55
@santus444 Unless the IDE starts freezing again on you, we don't need the logs.
