### ISSUE TITLE
Findings are classified by time

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#333] opened 2023-07-25 20:22 UTC
In VS Code, we've added this time-based listing that puts older findings into their own section:

![Image](https://user-images.githubusercontent.com/573108/256027501-a369e6b5-bb75-4b4c-8d91-90f0ff2453fa.png)

We need a similar implementation in JetBrains.

**Comment by dustinbyrne** [comment] 2023-07-26 14:17
Needs spec

**Comment by dustinbyrne** [comment] 2023-08-07 20:10
This looks to be a duplicate of https://github.com/getappmap/appmap-intellij-plugin/issues/328

**Closed** 2023-08-08 18:52 UTC
Labels: intellij-analysis
