### ISSUE TITLE
AppMaps should appear in AppMap toolbar after remote recording

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#312] opened 2023-06-22 17:36 UTC
To recreate:
1. Make a fresh clone of [spring-petclinic](https://github.com/spring-projects/spring-petclinic)
2. Open the fresh copy of spring-petclinic in IntelliJ with AppMap installed
3. When prompted, open as a Maven project
4. Navigate to `PetClinicApplication.java` and then `Run with AppMap`
5. Create a remote recording (I named it `test` but that shouldn't matter...)

Then you'll see that the remote recording opens in the editor and the AppMap file is indexed by the indexer, but the AppMap is not present in the AppMap toolbar:

![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/45714532/434a3757-9875-446a-adee-ba9fde8df20b)

**Comment by jansorg** [comment] 2023-07-21 10:15
This is caused by a missing name in the appmap.json file.

**Comment by jansorg** [comment] 2023-07-25 09:49
@ahtrotta The Java agent does not set the name property in the AppMap JSON it sends to the plugin. Previously, we were not using this property to detect the presence of AppMaps. But now we do and this change made this bug visible in the plugin.
Fixing the agent will fix this problem, too.

**Comment by kgilpin** [comment] 2023-07-25 13:08
Since the plugin is retrieving the remote recording can’t it set the name
field?

**Comment by jansorg** [comment] 2023-07-26 14:19
Conclusion of our discussion: Always set the `name` property in the new AppMap JSON

**Comment by jansorg** [comment] 2023-07-28 11:53
I tried to reproduce this again:
- With spring-petclinic Maven, everything worked as expected
- With spring-petclinic Gradle, it failed to show the AppMap, because the storage location is wrong.

**Comment by jansorg** [comment] 2023-08-11 12:48
@ahtrotta I moved this back to "Will do", because the latest PRs should fix this issue. Could you please close this if it's working for your now?

**Closed** 2023-08-15 15:36 UTC
Labels: bug
